if Code.ensure_loaded?(Phoenix.LiveView) do
  defmodule Localize.LiveView do
    @moduledoc """
    A LiveView `on_mount` hook that sets the locale of a LiveView process.

    A live navigation mounts a new LiveView without an HTTP request, so the plugs that set the locale from the route do not run, and the session still holds the locale of the page the navigation started from.

    This hook first sets the locale from the session, like `Localize.Plug.put_locale_from_session/2`. It then attaches a `handle_params` hook that sets the locale of the route: the locale of a route generated by `Localize.Routes.localize/1`, and the session locale for any other route.

    The `handle_params` hook runs after `mount/3`, before the first render and on each live patch. Build text that depends on the locale in `handle_params/3`, not in `mount/3`, and assign it: a live patch re-renders only the parts of the template whose assigns changed.

    ### Options

    * `:gettext` is a Gettext backend module or a list of Gettext backend modules on which the locale will be set. The default is `[]` (no Gettext backends).

    ### Example

        live_session :default, on_mount: [{Localize.LiveView, gettext: MyAppWeb.Gettext}] do
          localize do
            live "/dashboard", DashboardLive
          end
        end

    """

    @doc false
    def on_mount(options, _params, session, socket) do
      _ = Localize.Plug.put_locale_from_session(session, options)

      {:cont,
       Phoenix.LiveView.attach_hook(socket, __MODULE__, :handle_params, fn _params, uri, socket ->
         put_locale(socket, URI.parse(uri), session, options)
         {:cont, socket}
       end)}
    end

    # A live patch to a route outside `localize/1` restores the session
    # locale, as a mount of that route would.
    defp put_locale(socket, %URI{host: host, path: path}, session, options) do
      case Phoenix.Router.route_info(socket.router, "GET", path_info(socket.endpoint, path), host) do
        %{localize_locale: locale} -> Localize.Plug.put_locale(locale, options)
        _other -> Localize.Plug.put_locale_from_session(session, options)
      end
    end

    # The router matches decoded path segments without the endpoint's
    # script name, as LiveView does when it matches a route.
    defp path_info(endpoint, path) do
      segments = for segment <- String.split(path, "/"), segment != "", do: URI.decode(segment)
      strip_prefix(endpoint.script_name(), segments)
    end

    defp strip_prefix([segment | prefix], [segment | segments]),
      do: strip_prefix(prefix, segments)

    defp strip_prefix([], segments), do: segments
    defp strip_prefix(_prefix, _segments), do: nil
  end
end
