if Code.ensure_loaded?(Phoenix.LiveView) do
  defmodule Localize.LiveView do
    @moduledoc """
    A LiveView `on_mount` hook that sets the locale of a LiveView process.

    A live navigation mounts a new LiveView without an HTTP request, so the plugs that set the locale from the route do not run, and the session still holds the locale of the page the navigation started from.

    This hook first sets the locale from the session, like `Localize.Plug.put_locale_from_session/2`. It then attaches a `handle_params` hook that, on a route generated by `Localize.Routes.localize/1`, sets the locale of that route. The `handle_params` hook runs before every render, after `mount/3`: text that depends on the locale is best built in `handle_params/3` or in the template.

    ### Options

    * `:gettext` is a Gettext backend module or a list of Gettext backend modules on which the locale will be set. The default is `[]` (no Gettext backends).

    ### Example

        live_session :default, on_mount: [{Localize.LiveView, gettext: MyAppWeb.Gettext}] do
          localize do
            live "/dashboard", DashboardLive
          end
        end

    """

    @doc false
    def on_mount(options, _params, session, socket) do
      _ = Localize.Plug.put_locale_from_session(session, options)

      {:cont,
       Phoenix.LiveView.attach_hook(socket, __MODULE__, :handle_params, fn _params, uri, socket ->
         put_locale_from_route(socket, URI.parse(uri), options)
         {:cont, socket}
       end)}
    end

    # The router matches decoded path segments without the endpoint's
    # script name, as Phoenix does for the request itself.
    defp put_locale_from_route(socket, %URI{host: host, path: path}, options) do
      path_info = for segment <- String.split(path, "/"), segment != "", do: URI.decode(segment)
      path_info = Enum.drop(path_info, length(socket.endpoint.script_name()))

      case Phoenix.Router.route_info(socket.router, "GET", path_info, host) do
        %{localize_locale: locale} -> Localize.Plug.put_locale(locale, options)
        _other -> :ok
      end
    end
  end
end
